insert into states (id, name, abbreviation) values (11, 'Rond\u00f4nia', 'RO');
insert into states (id, name, abbreviation) values (12, 'Acre', 'AC');
insert into states (id, name, abbreviation) values (13, 'Amazonas', 'AM');
insert into states (id, name, abbreviation) values (14, 'Roraima', 'RR');
insert into states (id, name, abbreviation) values (15, 'Par\u00e1', 'PA');
insert into states (id, name, abbreviation) values (16, 'Amap\u00e1', 'AP');
insert into states (id, name, abbreviation) values (17, 'Tocantins', 'TO');
insert into states (id, name, abbreviation) values (21, 'Maranh\u00e3o', 'MA');
insert into states (id, name, abbreviation) values (22, 'Piau\u00ed', 'PI');
insert into states (id, name, abbreviation) values (23, 'Cear\u00e1', 'CE');
insert into states (id, name, abbreviation) values (24, 'Rio Grande do Norte', 'RN');
insert into states (id, name, abbreviation) values (25, 'Para\u00edba', 'PB');
insert into states (id, name, abbreviation) values (26, 'Pernambuco', 'PE');
insert into states (id, name, abbreviation) values (27, 'Alagoas', 'AL');
insert into states (id, name, abbreviation) values (28, 'Sergipe', 'SE');
insert into states (id, name, abbreviation) values (29, 'Bahia', 'BA');
insert into states (id, name, abbreviation) values (31, 'Minas Gerais', 'MG');
insert into states (id, name, abbreviation) values (32, 'Esp\u00edrito Santo', 'ES');
insert into states (id, name, abbreviation) values (33, 'Rio de Janeiro', 'RJ');
insert into states (id, name, abbreviation) values (35, 'S\u00e3o Paulo', 'SP');
insert into states (id, name, abbreviation) values (41, 'Paran\u00e1', 'PR');
insert into states (id, name, abbreviation) values (42, 'Santa Catarina', 'SC');
insert into states (id, name, abbreviation) values (43, 'Rio Grande do Sul', 'RS');
insert into states (id, name, abbreviation) values (50, 'Mato Grosso do Sul', 'MS');
insert into states (id, name, abbreviation) values (51, 'Mato Grosso', 'MT');
insert into states (id, name, abbreviation) values (52, 'Goi\u00e1s', 'GO');
insert into states (id, name, abbreviation) values (53, 'Distrito Federal', 'DF');
